### PR TITLE
fix: slash command cannot load

### PR DESCRIPTION
**Pull request by sus2790**
[CHANGELOG](https://github.com/HBYC-Team/Discord-Bot-Examples/blob/master/CHANGELOG.md) 記得寫
*暫時標記為草稿，指令等待確認

### CODE REVIEW

**Comment by sus2790** [comment]
大概好了

**Comment by dragonyc1002** [comment]
我會在有空整理完這份 repo 後，且再行確認後 merge ，在那之前還請先等我一下。

**Review by dragonyc1002 — APPROVED** [review]

**Comment by dragonyc1002** [comment]
Noted the Pull Request as ready to be merged. The repository may be cleaned up by the end of this month. After that, I will take the further actions.

**Review by sus2790 — COMMENTED** [review]
lgtm

**Pull request closed without merging**
